// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"golang_learn/go_wire/internal/config"
	"golang_learn/go_wire/internal/db"
	"golang_learn/go_wire/model"
)

// Injectors from wire.go:

func InitApp() (*model.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	sqlDB, cleanup, err := db.NewDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	app := model.NewApp(sqlDB)
	return app, func() {
		cleanup()
	}, nil
}
